### ISSUE TITLE
RESTful Institution Info?

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/keycloak-rest-services#15]
Right now, whenever an institution is added to the MoU Dashboard system, we have to restart the DB server. The list of institutions is imported from https://github.com/WIPACrepo/keycloak-rest-services/blob/master/keycloak_setup/icecube_setup.py, so this is static.

Is there some kind of REST service in the works that can replace this static limitation?

**Comment by dsschult** [comment]
When we get around to deploying Keycloak, that has a REST interface which can provide the list of institutions.  And since you'll probably be switching the MoU app to use auth from there, it should be fairly easy to query the Keycloak REST API as well.

**Comment by ric-evans** [comment]
Alright, great! That will solve that :+1:
