### ISSUE TITLE
split repository

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/keycloak-rest-services#50]
Consider separating the repository into at least two pieces:

1. `krs` python library
2. user management website and docs

Could also consider the `actions` cron jobs as a third piece.

---

Pros:
- `krs` version doesn't keep getting bumped for website changes
- "smaller" test suite for each repo is faster

Cons: ???

**Comment by ric-evans** [comment]
I suggested something similar in https://github.com/WIPACrepo/wipac-dev-tools/issues/20. I called it `wipac-krs-utils` for PyPI
